### ISSUE TITLE
Data aggregation

### ISSUE THREAD

**Issue by mariuszzak** [ludwikbukowski/telemetry_influxdb#17]
Hi @ludwikbukowski,

Thank you so much for providing this great library! :) 

I would like to ask if there was any specific reason why you decided not to aggregate the data before pushing to InfluxDB?
Did you consider to implement the `Telemetry.Metrics` interface?

Thanks in advance!

**Comment by ludwikbukowski** [comment]
Approach that we decided with @arkgil was that InfluxDB is rather "event driven" and its better to send pure events to influxdb and let the Influx's end user create metrics, as it gives solid tools for metrics management

**Comment by mariuszzak** [comment]
Thank you for your quick response! 
The problem I see is when we would like to have a metric that is based on events occurring very frequently, e.g. the average duration of a function invocation calculated per each minute. In case a function is invoked lets say 10k times per second we would have to send tons of data to InfluxDB. 

Do you have any experience with such cases? I would appreciate any suggestion how I could deal with this problem.

**Comment by arkgil** [comment]
@mariuszzak you could implement in-process aggregation yourself: take a look at how e.g. OpenTelemetry does it https://github.com/open-telemetry/opentelemetry-erlang/blob/master/src/ot_metric_aggregator_sum.erl.

If you want to limit the amount of data pushed to Influx, you could also consider sampling, where only a subset of the data is sent.

Anyway, you could do either of those yourself based on the events you want to measure, emit an event with  a sample/aggregated data, and have this reporter subscribe to these events so that they get pushed to Influx.

**Comment by mariuszzak** [comment]
Thank you so much for your response! I've solved the problem exactly the same way as you suggested ;)

Thank you for your help!
